Feat/navigation
Jeysieeeee/Main-Activity pull request #5
Opened 2023-03-10 06:56 UTC by Jeysieeeee

2023-03-10 07:07 UTC, edwinpergis requested changes

2023-03-10 07:07 UTC, edwinpergis commented on Style.tsx
> +    // marginTop: 130,
remove unused code

2023-03-10 07:07 UTC, edwinpergis commented on app/index.tsx
> +export default function Page() {
use arrow function

2023-03-10 07:07 UTC, edwinpergis commented on app/tabs/message.tsx
> +export const message = () =>
function and component name should start big letter

2023-03-10 07:07 UTC, edwinpergis commented on app/tabs/notification.tsx
> +export const notification = () =>
function and component name should start big letter

2023-03-10 07:07 UTC, edwinpergis commented on app/tabs/record.tsx
> +export const record = () =>
function and component name should start big letter

2023-03-13 03:01 UTC, edwinpergis approved these changes

2023-03-13 03:09 UTC, jarapamikaella approved these changes

2023-03-13 03:09 UTC, merged